Task_9/HogwartsUniversity/HogwartsUniversity/Controllers/CoursesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HogwartsUniversity.Data;
using HogwartsUniversity.Models;
using Microsoft.AspNetCore.Cors.Infrastructure;
using HogwartsUniversity.Serviсes.ServiceInterfaces;

namespace HogwartsUniversity.Controllers
{
    public class CoursesController : Controller
    {
        private readonly ICourseService _courseService;

        public CoursesController(ICourseService courseService)
        {
            _courseService = courseService;
        }

        // GET: Courses 
        public async Task<IActionResult> Index()
        {
            var courseList = await _courseService.GetAllAsync();
            return View(courseList);
        }

        // GET: Courses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id is null) return NotFound();
            var groupsOfCourse = await _courseService.GetGroupsOfCourseAsync(id);
            if (groupsOfCourse is null) return NotFound();
            return View(groupsOfCourse);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Description")] Course course)
        {
            if (ModelState.IsValid)
            {
                await _courseService.CreateAsync(course);
                return RedirectToAction(nameof(Index));
            }
            return View(course);
        }

        // GET: Courses/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id is null) return NotFound();
            var courseToUpdate = await _courseService.GetByIdAsync(id);
            if (courseToUpdate is null) return NotFound();
            return View(courseToUpdate);
        }

        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id)
        {
            var courseToUpdate = await _courseService.GetByIdAsync(id);
            if (courseToUpdate is null) return NotFound();

            if (await TryUpdateModelAsync<Course>(courseToUpdate, "", 
                c => c.Name, c => c.Description))
            {
                try
                {
                    await _courseService.UpdateAsync(courseToUpdate);
                    return RedirectToAction(nameof(Index));
                }
                catch (DbUpdateException)
                {
                    ModelState.AddModelError("", "Unable to save changes. Try again!.");
                }
            }

            return View(courseToUpdate);
        }

        //GET: /Courses/Delete/CourseId
        public async Task<IActionResult> Delete(int? id)
        {
            if (id is null) return NotFound();
            var courseToDelete = await _courseService.GetByIdAsync(id);
            if (courseToDelete is null) return NotFound();
            return View(courseToDelete);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var courseToDelete = await _courseService.GetByIdAsync(id);
            if (courseToDelete is null) return NotFound();
            try
            {
                await _courseService.DeleteAsync(courseToDelete);
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateException ex)
            {
                return RedirectToAction(nameof(Delete), new { id = id, saveChangesError = true });
            }
        }
    }
}

Task_9/HogwartsUniversity/HogwartsUniversity/Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HogwartsUniversity.Data;
using HogwartsUniversity.Models;
using HogwartsUniversity.Serviсes.ServiceInterfaces;

namespace HogwartsUniversity.Controllers
{
    public class GroupsController : Controller
    {
        private readonly IGroupService _groupService;

        public GroupsController(IGroupService groupService)
        {
            _groupService = groupService;
        }

        // GET: Groups
        public async Task<IActionResult> Index()
        {
            var universityContext = await _groupService.GetAllAsync();
            return View(universityContext);
        }

        // GET: Groups/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id is null) return NotFound();
            var group = await _groupService.GetStudentsOfGroupAsync(id);
            if (group is null) return NotFound();
            return View(group);
        }

        // GET: Groups/Create/courseId
        public IActionResult Create(int? id)
        {
            if (id is null) return NotFound();
            var newGroup = new Group { CourseId = (int)id };
            return View(newGroup);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int id, [Bind("CourseId,Name")] Group group)
        {
            group.CourseId = id;

            if (ModelState.IsValid)
            {
                await _groupService.CreateAsync(group);
                return Redirect($"/Courses/Details/{group.CourseId}");
            }

            return View(group);
        }

        // GET: Groups/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id is null) return NotFound();
            var groupToUpdate = await _groupService.GetByIdAsync(id);
            if (groupToUpdate is null) return NotFound();
            return View(groupToUpdate);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id)
        {
            var groupToUpdate = await _groupService.GetByIdAsync(id);
            if (groupToUpdate is null) return NotFound();

            if (await TryUpdateModelAsync<Group>(groupToUpdate, "", g => g.Name))
            {
                try
                {
                    await _groupService.UpdateAsync(groupToUpdate);
                    return Redirect($"/Courses/Details/{groupToUpdate.CourseId}");
                }
                catch (DbUpdateException ex)
                {
                    ModelState.AddModelError("", "Unable to save changes. Try again!.");
                }
            }

            return View(groupToUpdate);
        }

        // GET: Groups/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id is null) return NotFound();
            var groupToDelete = await _groupService.GetByIdAsync(id);
            if (groupToDelete is null) return NotFound();
            return View(groupToDelete);
        }

        // POST: Groups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int? id)
        {
            if (id is null) return NotFound();
            var groupToDelete = await _groupService.GetByIdAsync(id);
            if (groupToDelete is null) return NotFound();
            if (groupToDelete.Students.Count > 0) return View(groupToDelete);

            try
            {
                await _groupService.DeleteAsync(groupToDelete);
                return Redirect($"/Courses/Details/{groupToDelete.CourseId}");
            }
            catch (DbUpdateException ex)
            {
                return RedirectToAction(nameof(Delete), new { id = id, saveChangesError = true });
            }
        }
    }
}

Task_9/HogwartsUniversity/HogwartsUniversity/Views/Courses/Create.cshtml
@model HogwartsUniversity.Models.Course

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Course</h4>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Task_9/HogwartsUniversity/HogwartsUniversity/Views/Courses/Delete.cshtml
@model HogwartsUniversity.Models.Course

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Course</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Task_9/HogwartsUniversity/HogwartsUniversity/Views/Courses/Details.cshtml
@model HogwartsUniversity.Models.Course

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>
<div>
    <h4>@Model.Name course</h4>
    <h5>List of groups</h5>
    <a asp-controller="Groups" asp-action="Create" asp-route-id="@Model?.Id" class="btn btn-outline-primary"><i class="fas fa-plus"></i>Add new group</a>
    <table class="table">
        <tr>
            <th class="col-sm-3"></th>
            <th class="col-sm-5">Group name</th>
            <th>Action</th>
        </tr>
        @foreach (var item in Model.Groups)
        {
            <tr>
                <td></td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    <a asp-controller="Groups" asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-controller="Groups" asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-controller="Groups" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </table>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Task_9/HogwartsUniversity/HogwartsUniversity/Views/Courses/Edit.cshtml
@model HogwartsUniversity.Models.Course

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Course</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Task_9/HogwartsUniversity/HogwartsUniversity/Views/Courses/Index.cshtml
@model IEnumerable<HogwartsUniversity.Models.Course>

@{
    ViewData["Title"] = "Index";
}

<h1>Courses</h1>

<p>
    <a asp-action="Create" class="btn btn-outline-primary"><i class="fas fa-plus"></i>Create new course</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>